resources:
- name: noaa-weather-pipeline 
  type: git
  icon: github
  source:
    uri: https://github.com/ksmith211/noaa-weather.git

jobs:
- name: unit-test-frontend 
  plan:
  - get: noaa-weather-pipeline 
    trigger: true # trigger on every push to repo
  - task: install-frontend-dependencies
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # pass concourse-examples into this task step
      - name: noaa-weather-pipeline
      run:
        path: ls
        args: []
