resources:
- name: noaa-weather-pipeline 
  type: git
  icon: github
  source:
    uri: https://github.com/ksmith211/noaa-weather.git

jobs:
- name: install-frontend-dependencies 
  plan:
  - get: noaa-weather-pipeline 
  - task: cat-readme
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs: # pass concourse-examples into this task step
      - name: noaa-weather-pipeline
      run:
        path: cat
        args: ["concourse-examples/README.md"]
